
package br.com.pedcrm.soapClient;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ProdutoControllerService", targetNamespace = "http://controllers/", wsdlLocation = "http://localhost:8080/SOAP-SERVER/ProdutoController?wsdl")
public class ProdutoControllerService
    extends Service
{

    private final static URL PRODUTOCONTROLLERSERVICE_WSDL_LOCATION;
    private final static WebServiceException PRODUTOCONTROLLERSERVICE_EXCEPTION;
    private final static QName PRODUTOCONTROLLERSERVICE_QNAME = new QName("http://controllers/", "ProdutoControllerService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/SOAP-SERVER/ProdutoController?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        PRODUTOCONTROLLERSERVICE_WSDL_LOCATION = url;
        PRODUTOCONTROLLERSERVICE_EXCEPTION = e;
    }

    public ProdutoControllerService() {
        super(__getWsdlLocation(), PRODUTOCONTROLLERSERVICE_QNAME);
    }

    public ProdutoControllerService(WebServiceFeature... features) {
        super(__getWsdlLocation(), PRODUTOCONTROLLERSERVICE_QNAME, features);
    }

    public ProdutoControllerService(URL wsdlLocation) {
        super(wsdlLocation, PRODUTOCONTROLLERSERVICE_QNAME);
    }

    public ProdutoControllerService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, PRODUTOCONTROLLERSERVICE_QNAME, features);
    }

    public ProdutoControllerService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ProdutoControllerService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ProdutoController
     */
    @WebEndpoint(name = "ProdutoControllerPort")
    public ProdutoController getProdutoControllerPort() {
        return super.getPort(new QName("http://controllers/", "ProdutoControllerPort"), ProdutoController.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ProdutoController
     */
    @WebEndpoint(name = "ProdutoControllerPort")
    public ProdutoController getProdutoControllerPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://controllers/", "ProdutoControllerPort"), ProdutoController.class, features);
    }

    private static URL __getWsdlLocation() {
        if (PRODUTOCONTROLLERSERVICE_EXCEPTION!= null) {
            throw PRODUTOCONTROLLERSERVICE_EXCEPTION;
        }
        return PRODUTOCONTROLLERSERVICE_WSDL_LOCATION;
    }

}
